### ISSUE TITLE
#가입신청 페이지입니다# #Here is sign-up page#

### ISSUE THREAD

**Issue by HmHmmHm** [organization/SignUp#1]
안녕하세요, 여기는 오가니제이션 가입신청 페이지입니다.
'오가니제이션'은 포켓마인 플러그인 개발을 목적으로 합니다.
여러분은 '오가니제이션'에 가입하면 만드는 프로젝트들을 직접 수정할 수 있습니다.

Welcome, this is Organization sign up page.
'Organization' is purposed to develop PocketMine plugins.
You can directly modify organization projects if you join and work with us.

우리는 많은 것들을 개발하고 있습니다.
만약 포켓마인에 열정을 갖고 있으면, 우리와 함께 해주세요!

We are developing a lot of things.
Join us if you have a passion for PocketMine!
###### 아래사항을 기입하여 주시기 바랍니다.
1. 참여목적: 
2. 어떤걸 개발해보고 싶나요?: 
3. 당신은 다른 개발자들과 공동개발 하는 것에 동의합니까?: 
###### Please fill in the fields below.
1. Join purpose: 
2. What do you want to develop?:
3. Do you agree to jointly develop with other developers?:

**Comment by ghost** [comment]
1, 참여목적:궁금한것은, 물어보고 또한 개발에 참여하고 싶기 때문입니다
2. 어떤걸 개발해보고 싶나요?: 많이 부족하지만 채널 채팅 플러그인을 만들어보고 싶습니다.
/채널 채팅 생성, /채널 채팅 입장 *번, /모든 채널 입장
3. 당신은 다른 개발자들과 공동개발 하는 것에 동의합니까?:넵

**Comment by seompark** [comment]
## 참여목적

첫째로 포켓마인 서버들의 발전을 위해, 둘째로 개인적인 지식 추구의 욕구 때문입니다.

## 어떤걸 개발해보고 싶나요?

미개발된 다양한 미니게임들, PC에서 구현되었지만 PE는 아직인 수많은 플러그인들

## 당신은 다른 개발자들과 공동개발 하는 것에 동의합니까?

네

**Comment by HmHmmHm** [comment]
@ZINGDING  @Stabind 두분 모두 카카오톡 아이디 가지고 계시면 hmkakao 연락 부탁드립니다..!

**Comment by Laeng** [comment]
1. 참여목적: 

```
한국 PocketMine-MP 의 발전에 기여하고 다양한 아이디어를 오가니제이션과 함께 발전시키고 싶습니다.
```
1. 어떤걸 개발해보고 싶나요?

```
다양한 컨텐츠 플러그인을 개발하고 있으며 더욱 재미난 플러그인을 지속적으로 개발하고 싶습니다.
```
1. 당신은 다른 개발자들과 공동개발 하는것에 동의합니까?

```
네  
```

**Comment by SoulPE** [comment]
참여목적: 플러그인 개발을 통한 포켓마인 발전 및 서버 개발
어떤걸 개발해보고 싶나요?: 대규모 플러그인 ( 미니게임, 등등)
당신은 다른 개발자들과 공동개발 하는 것에 동의합니까?:( 당근입니다 )

**Comment by HmHmmHm** [comment]
@Laeng @SoulPE  hmkakao 카카오 연락 부탁드립니다..!

**Comment by mu-hun** [comment]
- 참여목적

```
해당 그룹에 기여를 하고 싶어서 지원을 했습니다.
(사실 깃허브 상태가 이 그룹으로 도배가 되서 뭔일인가 싶어서..)
```
- 어떤걸 개발해보고 싶나요?

```
흠.. 제가 PocketMine 개발에 익숙하지 않아서 개발해보고 싶은건 딱히 없고..
다른 분의 코드리뷰 정도 가능할것 같습니다.
```

플러그인 개발과 
- 당신은 다른 개발자들과 공동개발 하는 것에 동의합니까?:

```
네 당연합니다.
```

**Comment by HmHmmHm** [comment]
@yale2a1 대환영입니다...8ㅅ8
 hmkakao 카카오 연락 부탁드립니다..!

**Comment by with0624** [comment]
참여목적:PoketMine을 발전시키기 위해서입니다
어떤걸 개발해보고 싶나요?:경제에 대한 대규모서버를 운영할 수 있는 플러그인을 개발시키고 싶습니다.
당신은 다른 개발자들과 공동개발 하는 것에 동의합니까?:네 당연합니다

**Comment by HmHmmHm** [comment]
@with0624 hmkakao 카카오 연락 부탁드려요~

**Comment by psh3253** [comment]
1.참여목적: PocketMine을 더욱더 발전시키고 다양한 아이디어로 여러 개발자들과 함께 개발해보고 싶습니다.
2.어떤걸 개발해보고 싶나요?: 자동으로 운영되는 각종 미니게임 플러그인을 만들고 싶습니다.
3.당신은 다른 개발자들과 공동개발 하는 것에 동의합니까?: 당연합니다

**Comment by ghost** [comment]
참여목적: 참여하여서 깃허브조직 인원과 함께 플러그인을 개발하고 싶습니다.
어떤걸 개발해보고 싶나요?:파티플러그인을 첫번째로 만들고 싶고요 그리고 이모임으로 통해 플러그인 공부를 더열심히하여 플러그인 개발을 하여 공유하고 싶습니다.
당신은 다른 개발자들과 공동개발 하는 것에 동의합니까?:네!!

**Comment by HmHmmHm** [comment]
@psh3253 @zicwoboo 두분 모두 오전/오후 중으로 hmkakao 카톡 연락부탁드립니다.!

**Comment by Wokotuk** [comment]
1.참여목적 : PocketMine 발전 을 하고싶고 다른 개발자와 같이 활동하고 싶습니다

2.어떤걸 개발해보고 싶나요? : 경제서버에 필요한 플러그인 (대규모) 을 만들고 싶습니다.

3.당신은 다른 개발자들과 공동개발 하는 것에 동의합니까? : 동의합니다 :)

**Comment by Lavender204** [comment]
- 참여 목적: MCPE의 대표 서버 구동기인 PocketMine-MP의 플러그인 생태계에 도움을 주고 싶습니다.
  PocketMine-MP는 플러그인이 많기는 하지만 아직까지 PC 버전 마인크래프트에 비해서 플러그인이 좀 적은 것 같습니다.
  PC 버전의 마인크래프트 만큼의 방대한 플러그인 생태계를 구축하고 싶습니다.
- 어떤 걸 개발해보고 싶나요?: 여러 가지 플러그인들을 개발하고 싶지만 그 중에서 정말로 개발하고 싶은 것은 트리거 플러그인 (PC 마인크래프트의 VariableTriggers 플러그인) 입니다.
  예전에 PC 마인크래프트 서버를 구축했을때 트리거 플러그인을 많이 사용했는데 MCPE 서버를 보니 트리거 같은 플러그인을 찾을 수가 없어서 살짝 불편한 감이 있었습니다.
  그렇기 때문에 전 트리거 플러그인을 우선으로 개발하고 싶습니다.
- 당신은 다른 개발자들과 공동개발 하는 것에 동의합니까?: 네! 물론입니다! :D

**Comment by Riandanadana** [comment]
1.참여 목적: 플러그인공부와 php 언어 공부를 시작한지 1주일이 지났습니다. 여기 가입하면 실력 향생에 도움이 될거 같아서 가입 신청 했습니다. (php초보도 되..죠?)
2.어떤걸 개발해보고 싶나요?: 기회가 된다면 컴퓨터 마크와 비슷하게 만들고 싶습니당
3.당신은 다른 개발자들과 공동개발 하는 것에 동의합니까? : 당근 동의 하죠!

**Comment by HmHmmHm** [comment]
@Wokotuk @RichVillage @Riandanadana hmkakao 카톡 연락부탁드립니다.!

**Comment by Matunserver** [comment]
참여목적: 플러그인 오류수정과 제작에 큰디딤돌이 되리라 예상하며.
어떤걸 개발해보고 싶나요?: 현재없는 컨텐츠 플러그인 ZombieGame
당신은 다른 개발자들과 공동개발 하는 것에 동의합니까?: 물론입니다!

**Comment by mpcream** [comment]
참여목적:플러그인개발하여 여러사람에게 도움을 주거나 정말 하고 싶은 거였기때문에 입니다
어떤걸 개발해보고 싶나요?:워프플러그인입니다 앞에 서있기만하면표지판이 있는데도터치안하고 가는플러그인입니다,자동차처럼 타면 앞으로 갈수있는 레일없는 플러그인입니다
당신은 다른 개발자들과 공동개발 하는 것에 동의합니까?:네

**Comment by HmHmmHm** [comment]
@Matunserver @mpcream hmkakao 연락부탁드립니다~

**Comment by cr0sh** [comment]
참여목적: 당연히 플긴 개발!
개발 대상: 현재는 텔레그램 봇이 1순위
공동개발: OK(라이센스는 강력한 GPL/Affeno GPL 채택 예정)

**Comment by kerasise** [comment]
참여목적: 플러그인 개발하여 쉽고 어렵든 플러그인을 만드는 걸 좋아서해  때문입니다 
어떤걸 개발하고 싶나요? : 네 블럭으로 명령어 및  보안과 관련된 것을 만들고 싶습니다.
공동 개발  : 네 당연히 참여하겠습니다.

**Comment by Xesame** [comment]
참여목적: 
제가 만드는 플러그인들은 기능이 거의 없기에, 개발 순서같은 개념이 없습니다. 고로 저보다 뛰어나신 플기너분들이 플러그인을 어떤 순서로, 어떤 방식으로 만드는지 배우고 싶은게 한가지 목적이고, 

다른 플러그인들, 혹은 제 자작 플러그인 공동 개발을 통해 제 실력을 쌓고 각종 서버들에 도움이 되는것이 제 최종 목적입니다.

어떤걸 개발해보고 싶나요?: 

PE에서 구현 가능한 범위 내에서 스마트무빙을 개발해보고 싶습니다.

당신은 다른 개발자들과 공동개발 하는 것에 동의합니까?: 네.

**Comment by sJimin** [comment]
1.참여목적: PMMP 서버를 애용하는 사람으로써 pmmp의 불편한점을 즉각 플러그인으로 고쳐 쓰고 싶고
아직 나오지 않은 포션 인첸트 레드스톤 이런것들을 여러가지 수단을 동원하여 구현 시키고싶은것이 제 목적이다.

2.어떤걸 개발해보고 싶나요?:  
pmmp서버의 기본적인 오류들을 해결한후 다른 사람들과는 색다른것들을 만들고 싶다.
생각치도 못한것들 혹은 쉽고 단순하지만서도 유용한것들 위주로 만들예정이다.

3.당신은 다른 개발자들과 공동개발 하는 것에 동의합니까?:  필요에 따라 동의합니다.

Please fill in the fields below.
1.Join purpose: As I love pmmp server, I want to fix the pmmp's problems.
2.What do you want to develop?: "Creativity"
3.Do you agree to jointly develop with other developers?:
Yes

**Comment by yale2a1** [comment]
@sJimin "yale2a1rlaang" 연락 바랍니다~

**Comment by ghost** [comment]
1. 아무래도, 플러그인 개발을 할때 저 혼자서 해왔기 때문에 다른 분들이랑 협력해서 하는등 협동심을 기르고 싶습니다.
2. 딱히 아직 개발하고 싶은 요소는 아직 없습니다.
3. 네.

**Comment by yale2a1** [comment]
@SiaAs "yale2a1rlaang" 연락 바랍니다~

**Comment by ghost** [comment]
- 참여목적:
  - 국내 포켓마인 서버 발전 및 개인적 능력 향상이 목적입니다. 
- 어떤걸 개발해보고 싶나요?:
  - 미니게임이 주 기능인 플러그인, 서버 패킷 캡쳐 플러그인
- 당신은 다른 개발자들과 공동개발 하는 것에 동의합니까?:
  - 대답: 네

**Comment by yale2a1** [comment]
@Xesame 'yale2a1rlaang' 연락 바랍니다~

**Comment by nesgohood** [comment]
1.참여목적: 플러그인의 다양성을 더욱 발전 및 초보 탈출
2.어떤걸 개발해보고 싶나요?: RPG 플러그인, 보안 플러그인
3.당신은 다른 개발자들과 공동개발 하는 것에 동의합니까?: 넵

**Comment by yale2a1** [comment]
@nesgohood 'yale2a1rlaang' 연락 바랍니다~

**Comment by Joker1234** [comment]
아래사항을 기입하여 주시기 바랍니다.

참여목적: 플러그인 개발!
어떤걸 개발해보고 싶나요?:왕국게임 여러미니게임(현재 크레이지아케이드 만들고싶음..)
당신은 다른 개발자들과 공동개발 하는 것에 동의합니까?:네!

**Comment by ZINGDING** [comment]
@Joker1234 
카카오톡 "mshs0212"로 연락주세요~

**Comment by Kintiru** [comment]
참여목적:

PMMP플러그인 언어(php)의 지식 습득 + 좋은 경험이 될거 같아서
플러그인 초보도....되죠..? 큼..

어떤걸 개발해보고 싶나요?:

현재 Bj악어님의 마크에이지 및 다른 컨텐츠 / 클리어 할때마다 경로가 바뀌는 미로 플러그인 /
FPS 서버 플러그인 구현 / 판타지 서버 플러그인 구현 / 용암태러 및 tnt태러 당하였을때
랙이 않걸리고 램 및 cpu사용량 이 높아지지 아니하게 하는 플러그인

당신은 다른 개발자들과 공동개발 하는 것에 동의합니까?:
넵!

**Comment by MuhunKim** [comment]
@junee1163 yale2a1rlaang' 연락 바랍니다.

**Comment by Blacklater** [comment]
참여목적 : 
PocketMine-MP 플러그인은 못만들어도 
마크PE서버 구동기인 Nukkit 플러그인을 개발하고싶습니다.
큼 어제 자바책사서 엄청나게 공부하고있습니다.
다른 플기너분들에게 지식 과 좋은경험이 될거 같아서
플러그인 초보도 가능하죠?...

어떤걸 개발해보고 싶나요?:
Hm님의 공지/땅/워프/도박/보안플긘/유체>고체플긘 과 RPG플긘/캐쉬플긘/후원코인플긘
같은거를 Nukkit용플긘을 만들고싶습니다!

당신은 다른 개발자들과 공동개발을 하는 것에 동의합니까?:
넵!! 당연합니다!

**Comment by MackistyTri** [comment]
참여목적:평소에도 프로그래밍쪽으로는 상당히 관심히 많고 그 욕구를 충족 시키기 위해 아직 초보지만 해보려고 합니다.

어떤걸 개발해보고 싶나요?:저는 MinecraftPE를 즐기는 유저에게 보다 쉽고 편리한 플러그인을 공급하고 싶습니다. 예를 들자면 PC상에는 존재하지만 PE상에는 존재하지 않는 플러그인이랄까?

당신은 다른 개발자들과 공동개발 하는 것에 동의합니까?:네. (초보인데 괜찮으실지.)

**Comment by MuhunKim** [comment]
@Blacklater @MackistyTri 'yale2a1rlaang' 연락 바랍니다.

**Comment by ghost** [comment]
1.참여목적 : 포켓마인에 대한 많은 지식을 얻고 싶습니다.
2.어떤걸 개발해보고 싶나요? : 클라이언트 애드온과의 연동 플러그인
3.당신은 다른 개발자들과 공동개발 하는 것에 동의합니까? : 동의합니다!

**Comment by MuhunKim** [comment]
@pentaminum yale2a1rlaang 연락바랍니다.

**Comment by BJWhiteWizard** [comment]
1.참여목적: 다른 플러그인 개발자들과 정보를 교환하고 모르는것은 더욱 알고 싶기 때문입니다.
2.어떤걸 개발해보고 싶나요?: FPS 플러그인, 커맨드블럭 플러그인...
3.당신은 다른 개발자들과 공동개발 하는 것에 동의합니까?: 네! 당연합니다!

**Comment by kmkm12345** [comment]
1, 참여목적:PocketMine에 대한 지식을 쌓고싶습니다.
2. 어떤걸 개발해보고 싶나요?: 실력은 부족하여도 PocketMine을 즐기는 유저들 모두 즐겁게 사용할수있는 플러그인을 개발해보고 싶습니다.예를 들자면 RPG플러그인이라던가 총 플러그인 같은 플러그인정도?
3. 당신은 다른 개발자들과 공동개발 하는 것에 동의합니까?:넵!

**Comment by JaYuMan** [comment]
참여목적: 플러그인을 좀더 알고 싶고 더 적극적으로 개발을 해보고 싶었기 때문이다.
어떤걸 개발해보고 싶나요?: 다른유저분들이 불편하고 개선되었으면 하는 것을 개발하고 싶습니다.
당신은 다른 개발자들과 공동개발 하는 것에 동의합니까?:네

**Comment by mu-hun** [comment]
@JaYuMan @kmkm12345 @BJWhiteWizard 텔레그램 [@Betakim](http://telegram.me/BetaKim) 연락바랍니다.

**Comment by choihyunsu** [comment]
참여목적: MCPE에서의 플러그인 다양화를 위한 플러그인 개발을 배우고 싶습니다.
어떤걸 개발해보고 싶나요?: 공성전 서버에서 사용할수 있는 플러그인을 만들고 싶습니다.
당신은 다른 개발자들과 공동개발 하는 것에 동의합니까?: 당연하죠 공동개발로 피드백을 받아 완벽하게 만들고 싶습니다.

**Comment by mu-hun** [comment]
@choihyunsu 텔레그렘 [@Betakim](http://telegram.me/BetaKim) 연락바랍니다.

**Comment by ghost** [comment]
1. 참여목적: 플러그인 개발, 좋은 가르침
   2.어떤걸 개발해보고 싶나요?: 구체적으로는 현실과 동일화 시키는 플러그인 (ex : 발자국, 샤워 등)
   3.당신은 다른 개발자들과 공동개발 하는 것에 동의합니까?: 동의합니다.

**Comment by ParkChanSol** [comment]
1.참여목적: 포켓마인과 php 에 대해 자세히 알고 실력이 들면 플러그인을 개발하기 위해서

2.어떤걸 개발해보고 싶나요?: 미니게임 등(SkyWars, HungerGame 등-실력이 들면)

3.당신은 다른 개발자들과 공동개발 하는 것에 동의합니까?:네

지금은 hm 님의 강좌를 보며 열심히 배우고 있습니다

**Comment by nnnlog** [comment]
@HmHmmHm @ZINGDING 
참여목적: 플러그인을 배우면서 개발하고 싶습니다
어떤걸 개발해보고 싶나요?: 미니게임 위주
당신은 다른 개발자들과 공동개발 하는 것에 동의합니까?: 네!

**Comment by ghost** [comment]
#참여목적:지식+경험등을 쌓고싶어서/평소 파일소스들을 보고 혼자배워가기에는 베이스가 부족해서.
#어떤걸 개발해보고 싶나요?:날씨관련된 플러그인을 개발해보고싶다.
#당신은 다른 개발자들과 공동개발 하는 것에 동의합니까?:예

**Comment by seompark** [comment]
#6

**Comment by nnnlog** [comment]
#6

**Comment by mu-hun** [comment]
Lock conversation.
